export const OBJECT_CONFIGS = {
  oak_tree: {
    label: "Oak Tree",
    category: "tree",
    path: "/materials/oak_trees/scene.gltf",
    thumb: "/materials/oak_trees/textures/bark1_baseColor.png",
    cols: 1,
    rows: 1,
  },
  stylized_tree: {
    label: "Stylized Tree",
    category: "tree",
    path: "/materials/stylized_tree/scene.gltf",
    thumb: "/materials/stylized_tree/textures/leafes_Mat.001_baseColor.png",
    cols: 1,
    rows: 1,
  },
  asia_building: {
    label: "Asia Building",
    category: "building",
    path: "/materials/asia_building/scene.gltf",
    thumb: "/materials/asia_building/textures/build_01_baseColor.jpeg",
    cols: 2,
    rows: 2,
  },
  dakota_building: {
    label: "Dakota Building",
    category: "building",
    path: "/materials/dakota_building/scene.gltf",
    thumb: "/materials/asia_building/textures/concrete_baseColor.jpeg",
    cols: 2,
    rows: 2,
  },
  resort: {
    label: "Resort Villa",
    category: "building",
    path: "/materials/resort/scene.gltf",
    thumb: "/materials/resort/textures/porte_010___d_baseColor.jpeg",
    cols: 4,
    rows: 3,
  },
  blue_radison_resort: {
    label: "Blue Radison Resort",
    category: "building",
    path: "/materials/the_blue_radison_resort/scene.gltf",
    thumb:
      "/materials/the_blue_radison_resort/textures/brique_012_Wall_Entity_Material_baseColor.jpeg",
    cols: 2,
    rows: 4,
  },
  swimming_pool: {
    label: "Swimming Pool",
    category: "building",
    path: "/materials/swimming_pool.glb",
    thumb: null,
    cols: 4,  // 20 units wide — proper resort centrepiece
    rows: 3,
  },
  inflatable_pool: {
    label: "Inflatable Pool",
    category: "building",
    path: "/materials/inflatable_pool.glb",
    thumb: null,
    cols: 2,
    rows: 2,
  },
  beach_kit: {
    label: "Beach Kit",
    category: "building",
    path: "/materials/beach_kit.glb",
    thumb: null,
    cols: 2,
    rows: 2,
  },
  pool_float: {
    label: "Pool Float",
    category: "tree",
    path: "/materials/pool_float.glb",
    thumb: null,
    cols: 1,
    rows: 1,
  },
  beach_table: {
    label: "Beach Table",
    category: "tree",
    path: "/materials/beach_table.glb",
    thumb: null,
    cols: 1,
    rows: 1,
  },
  beach_boulder: {
    label: "Beach Boulder",
    category: "tree",
    path: "/materials/beach_boulder.glb",
    thumb: null,
    cols: 1,
    rows: 1,
  },
  simple_wooden_pier_or_dock: {
    label: "Wooden Pier",
    category: "building",
    path: "/materials/simple_wooden_pier_or_dock.glb",
    thumb: null,
    cols: 3,  // 15 wide
    rows: 6,  // 30 deep — reaches into water from beach edge
  },
  zsolnay_fountain: {
    label: "Fountain",
    category: "building",
    path: "/materials/zsolnay_fountain.glb",
    thumb: null,
    cols: 2,
    rows: 2,
  },
  airport_pack_total: {
    label: "Airport",
    category: "building",
    path: "/materials/airport_pack_total.glb",
    thumb: null,
    cols: 20, // 100 units wide — proper island airport scale
    rows: 12, // 60 units deep
  },
  road: {
    label: "Road",
    category: "building",
    path: "/materials/road.glb",
    thumb: null,
    cols: 6,  // 30-unit segment — long enough to chain visually
    rows: 2,
  },
  road_pack: {
    label: "Road Pack",
    category: "building",
    path: "/materials/road_pack.glb",
    thumb: null,
    cols: 10, // 50×50 central hub
    rows: 10,
  },
  road_template: {
    label: "Road (Curved)",
    category: "building",
    path: "/materials/road_template.glb",
    thumb: null,
    cols: 5,
    rows: 5,
  },
  low_road: {
    label: "Low Road",
    category: "building",
    path: "/materials/low_road.glb",
    thumb: null,
    cols: 6,  // same length as road for consistent look
    rows: 2,
  },
  cartoon_car: {
    label: "Car",
    category: "tree",
    path: "/materials/cartoon_car.glb",
    thumb: null,
    cols: 1,
    rows: 1,
  },
  fishing_boat: {
    label: "Fishing Boat",
    category: "tree",
    path: "/materials/fishing_boat.glb",
    thumb: null,
    cols: 2,
    rows: 2,
  },
  tow_boat: {
    label: "Tow Boat",
    category: "tree",
    path: "/materials/tow_boat.glb",
    thumb: null,
    cols: 2,
    rows: 3,
  },
  water_fountain: {
    label: "Water Fountain",
    category: "building",
    path: "/materials/water_fountain.glb",
    thumb: null,
    cols: 2,
    rows: 2,
  },
};
