export const OBJECT_CONFIGS = {
  oak_tree: {
    label: "Palm Tree (Tall)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_palmTall.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_palmTall_NE.png",
    cols: 1,
    rows: 1,
  },
  stylized_tree: {
    label: "Palm Tree (Short)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_palmDetailedShort.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_palmDetailedShort_NE.png",
    cols: 1,
    rows: 1,
  },
  pine_tree: {
    label: "Pine Tree",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_pineRoundA.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_pineRoundA_NE.png",
    cols: 1,
    rows: 1,
  },
  asia_building: {
    label: "Watchtower",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/tower-complete-small.glb",
    thumb: "/kenney_pirate-kit/Previews/tower-complete-small.png",
    cols: 2,
    rows: 2,
  },
  dakota_building: {
    label: "Lighthouse",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/tower-complete-large.glb",
    thumb: "/kenney_pirate-kit/Previews/tower-complete-large.png",
    cols: 2,
    rows: 2,
  },
  resort: {
    label: "Beach Bungalow",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-roof.glb",
    thumb: "/kenney_pirate-kit/Previews/structure-roof.png",
    cols: 3,
    rows: 3,
  },
  blue_radison_resort: {
    label: "Overwater Bungalow",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-platform-dock.glb",
    thumb: "/kenney_pirate-kit/Previews/structure-platform-dock.png",
    cols: 4,
    rows: 3,
  },
  beach_hut: {
    label: "Beach Hut (Open)",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure.glb",
    thumb: "/kenney_pirate-kit/Previews/structure.png",
    cols: 2,
    rows: 2,
  },
  castle_gate: {
    label: "Stone Gate",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/castle-gate.glb",
    thumb: "/kenney_pirate-kit/Previews/castle-gate.png",
    cols: 2,
    rows: 2,
  },
};
