export const OBJECT_CONFIGS = {
  oak_tree: {
    label: "Palm Tree (Tall)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_palmTall.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_palmTall_NE.png",
    cols: 1,
    rows: 1,
  },
  stylized_tree: {
    label: "Palm Tree (Short)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_palmDetailedShort.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_palmDetailedShort_NE.png",
    cols: 1,
    rows: 1,
  },
  pine_tree: {
    label: "Pine Tree (Round)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_pineRoundA.glb",
    thumb: "/kenney_nature-kit/Isometric/tree_pineRoundA_NE.png",
    cols: 1,
    rows: 1,
  },
  pine_tall: {
    label: "Pine Tree (Tall)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_pineTallA.glb",
    cols: 1,
    rows: 2,
  },
  pine_tall_b: {
    label: "Pine Tree (Tall B)",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_pineTallB.glb",
    cols: 1,
    rows: 2,
  },
  tree_fat: {
    label: "Fat Tree",
    category: "tree",
    path: "/kenney_nature-kit/Models/GLTF/tree_fat.glb",
    cols: 1,
    rows: 1,
  },
  palm_tree: {
    label: "Palm Tree",
    category: "tree",
    path: "/models/Palm tree.glb",
    cols: 1,
    rows: 1,
  },
  palm_bend: {
    label: "Bent Palm",
    category: "tree",
    path: "/kenney_pirate-kit/Models/GLB/palm-bend.glb",
    cols: 1,
    rows: 1,
  },
  palm_straight: {
    label: "Straight Palm",
    category: "tree",
    path: "/kenney_pirate-kit/Models/GLB/palm-straight.glb",
    cols: 1,
    rows: 1,
  },
  palm_detailed_bend: {
    label: "Detailed Palm (Bent)",
    category: "tree",
    path: "/kenney_pirate-kit/Models/GLB/palm-detailed-bend.glb",
    cols: 1,
    rows: 1,
  },
  palm_detailed_straight: {
    label: "Detailed Palm (Straight)",
    category: "tree",
    path: "/kenney_pirate-kit/Models/GLB/palm-detailed-straight.glb",
    cols: 1,
    rows: 1,
  },

  // ── Buildings ────────────────────────────────────────────────────────────
  asia_building: {
    label: "Watchtower",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/tower-complete-small.glb",
    thumb: "/kenney_pirate-kit/Previews/tower-complete-small.png",
    cols: 2,
    rows: 2,
  },
  dakota_building: {
    label: "Lighthouse",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/tower-complete-large.glb",
    thumb: "/kenney_pirate-kit/Previews/tower-complete-large.png",
    cols: 2,
    rows: 2,
  },
  resort: {
    label: "Beach Bungalow",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-roof.glb",
    thumb: "/kenney_pirate-kit/Previews/structure-roof.png",
    cols: 3,
    rows: 3,
  },
  blue_radison_resort: {
    label: "Overwater Bungalow",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-platform-dock.glb",
    thumb: "/kenney_pirate-kit/Previews/structure-platform-dock.png",
    cols: 4,
    rows: 3,
  },
  beach_hut: {
    label: "Beach Hut (Open)",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure.glb",
    thumb: "/kenney_pirate-kit/Previews/structure.png",
    cols: 2,
    rows: 2,
  },
  castle_gate: {
    label: "Stone Gate",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/castle-gate.glb",
    thumb: "/kenney_pirate-kit/Previews/castle-gate.png",
    cols: 2,
    rows: 2,
  },
  dock_platform: {
    label: "Dock Platform",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-platform.glb",
    cols: 2,
    rows: 2,
  },
  dock_small: {
    label: "Dock (Small)",
    category: "building",
    path: "/kenney_pirate-kit/Models/GLB/structure-platform-small.glb",
    cols: 2,
    rows: 2,
  },
  bungalow: {
    label: "Bungalow",
    category: "building",
    path: "/models/Bungalow.glb",
    cols: 3,
    rows: 3,
  },
  cottage: {
    label: "Cottage",
    category: "building",
    path: "/models/Cottage.glb",
    cols: 3,
    rows: 3,
  },
  house: {
    label: "House",
    category: "building",
    path: "/models/House.glb",
    cols: 3,
    rows: 3,
  },
  villa: {
    label: "Villa",
    category: "building",
    path: "/models/Villa.glb",
    cols: 4,
    rows: 4,
  },

  crab: {
    label: "Crab",
    category: "prop",
    path: "/models/Crab.glb",
    cols: 1,
    rows: 1,
  },
  flamingo: {
    label: "Flamingo",
    category: "prop",
    path: "/models/Flamingo.glb",
    cols: 1,
    rows: 1,
  },
  seagull: {
    label: "Seagull",
    category: "prop",
    path: "/models/Seagull.glb",
    cols: 1,
    rows: 1,
  },
  beach_ball: {
    label: "Beach Ball",
    category: "prop",
    path: "/models/beach ball.glb",
    cols: 1,
    rows: 1,
  },
  sun_lounger: {
    label: "Sun Lounger",
    category: "prop",
    path: "/kenney_nature-kit/Models/GLTF/bed.glb",
    cols: 1,
    rows: 1,
  },
  beach_umbrella: {
    label: "Beach Umbrella",
    category: "prop",
    path: "/kenney_nature-kit/Models/GLTF/tent_smallOpen.glb",
    cols: 1,
    rows: 1,
  },
  beach_rock_a: {
    label: "Beach Rock A",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/rocks-sand-a.glb",
    cols: 2,
    rows: 2,
  },
  beach_rock_b: {
    label: "Beach Rock B",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/rocks-sand-b.glb",
    cols: 2,
    rows: 2,
  },
  beach_rock_c: {
    label: "Beach Rock C",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/rocks-sand-c.glb",
    cols: 2,
    rows: 2,
  },
  rock_a: {
    label: "Rock A",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/rocks-a.glb",
    cols: 2,
    rows: 2,
  },
  rock_b: {
    label: "Rock B",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/rocks-b.glb",
    cols: 2,
    rows: 2,
  },
  campfire: {
    label: "Campfire",
    category: "prop",
    path: "/kenney_nature-kit/Models/GLTF/campfire_bricks.glb",
    cols: 1,
    rows: 1,
  },
  barrel: {
    label: "Barrel",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/barrel.glb",
    cols: 1,
    rows: 1,
  },
  boat_small: {
    label: "Row Boat",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/boat-row-small.glb",
    cols: 1,
    rows: 2,
  },
  lily: {
    label: "Water Lily",
    category: "prop",
    path: "/kenney_nature-kit/Models/GLTF/lily_large.glb",
    cols: 1,
    rows: 1,
  },
  flag_high: {
    label: "Flag (Tall)",
    category: "prop",
    path: "/kenney_pirate-kit/Models/GLB/flag-high.glb",
    cols: 1,
    rows: 1,
  },
  log_stack: {
    label: "Log Stack",
    category: "prop",
    path: "/kenney_nature-kit/Models/GLTF/log_stack.glb",
    cols: 1,
    rows: 1,
  },
};
